from exceptions.db import add_db_exception_handler
